import fs from "fs";
import path from "path";
import type { AppwriteConfig, Attribute } from "appwrite-utils";
import { MessageFormatter } from "./messageFormatter.js";

export class GoModelGenerator {
  constructor(private config: AppwriteConfig, private appwriteFolderPath: string) {}

  public generate(options: { baseOutputDirectory: string; verbose?: boolean }): void {
    const { baseOutputDirectory, verbose = false } = options;
    const goDir = baseOutputDirectory;
    if (!fs.existsSync(goDir)) fs.mkdirSync(goDir, { recursive: true });

    const collections = this.config.collections || [];
    for (const coll of collections) {
      const fileName = `${this.toSnake(coll.name)}.go`;
      const filePath = path.join(goDir, fileName);
      const code = this.generateStruct(coll.name, coll.attributes || []);
      fs.writeFileSync(filePath, code, { encoding: "utf-8" });
      if (verbose) MessageFormatter.success(`Go struct written to ${filePath}`, { prefix: "Schema" });
    }
  }

  private generateStruct(name: string, attributes: Attribute[]): string {
    const pascal = this.toPascal(name);

    const lines: string[] = [];
    // File doc comment noting datetime handling convention.
    lines.push(`// Code generated by appwrite-utils. DO NOT EDIT.`);
    lines.push(`// Appwrite datetime fields are represented as ISO 8601 strings.`);
    lines.push(`// (time.Time as ISO string) to avoid forcing a time import.`);
    lines.push(``);
    lines.push(`package models`);
    lines.push(``);
    lines.push(`type ${pascal} struct {`);

    // Base Appwrite system fields.
    lines.push("\tID        string `json:\"$id\"`");
    lines.push("\tCreatedAt string `json:\"$createdAt\"`");
    lines.push("\tUpdatedAt string `json:\"$updatedAt\"`");

    for (const attr of attributes) {
      if (!attr || !(attr as any).key) continue;
      const key = String((attr as any).key);
      const required = !!(attr as any).required;

      const enumComment = this.enumComment(attr);
      if (enumComment) lines.push(`\t${enumComment}`);

      const goType = this.mapAttributeToGoType(attr);
      const fieldName = this.toPascalField(key);
      const fieldType = required ? goType : `*${goType}`;
      const jsonTag = required ? `json:"${key}"` : `json:"${key},omitempty"`;
      lines.push(`\t${fieldName} ${fieldType} \`${jsonTag}\``);
    }

    lines.push(`}`);
    lines.push(``);
    return lines.join("\n");
  }

  private enumComment(attr: Attribute): string | null {
    const t = String((attr as any).type || "").toLowerCase();
    if (t !== "enum") return null;
    const els = Array.isArray((attr as any).elements) ? (attr as any).elements : [];
    if (els.length === 0) return null;
    return `// allowed: ${els.join(", ")}`;
  }

  private mapAttributeToGoType(attr: Attribute): string {
    const t = String((attr as any).type || "").toLowerCase();
    const isArray = !!(attr as any).array;
    let base: string;
    switch (t) {
      case "string":
      case "email":
      case "ip":
      case "url":
        base = "string";
        break;
      case "integer":
        base = "int64";
        break;
      case "double":
      case "float":
        base = "float64";
        break;
      case "boolean":
        base = "bool";
        break;
      case "datetime":
        // time.Time as ISO string; kept as string to avoid forcing a time import.
        base = "string";
        break;
      case "enum":
        // Go has no literal unions; allowed values are emitted as a line comment.
        base = "string";
        break;
      case "relationship": {
        const relType = (attr as any).relationType || "";
        base = relType === "oneToMany" || relType === "manyToMany" ? "[]string" : "string";
        break;
      }
      default:
        base = "string";
        break;
    }
    if (isArray && t !== "relationship") {
      base = `[]${base}`;
    }
    return base;
  }

  private toSnake(s: string): string {
    return s
      .replace(/([a-z0-9])([A-Z])/g, "$1_$2")
      .replace(/[^a-zA-Z0-9]+/g, "_")
      .replace(/_+/g, "_")
      .replace(/^_|_$/g, "")
      .toLowerCase();
  }

  private toPascal(s: string): string {
    return s
      .replace(/[^a-zA-Z0-9]+/g, " ")
      .split(" ")
      .filter(Boolean)
      .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
      .join("");
  }

  private toPascalField(s: string): string {
    return s
      .replace(/[^a-zA-Z0-9]+/g, " ")
      .split(" ")
      .filter(Boolean)
      .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
      .join("");
  }
}
